-- Generated from canonical-materials.json. Canonical definitions only: NO prices or availability.
-- Idempotent, additive: legacy records and all existing IDs are preserved.
begin;
insert into public.stores(id,name,website,active) values
('obi','OBI','https://www.obi.de',true),('bauhaus','BAUHAUS','https://www.bauhaus.info',true),('hornbach','HORNBACH','https://www.hornbach.de',true),('toom','toom','https://toom.de',true),('hagebau','hagebau','https://www.hagebau.de',true),('globus','Globus Baumarkt','https://www.globus-baumarkt.de',true),('hellweg','HELLWEG','https://www.hellweg.de',true)
on conflict(id) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:gipskarton-standard-12-5-1200-600-v1'))::uuid,'gipskarton-standard-12-5-1200-600-v1','Gipskartonplatte Standard 12,5 × 600 × 1200 mm','Gipskartonplatte Standard 12,5 × 600 × 1200 mm','Gipskartonplatte Standard 12,5 × 600 × 1200 mm','Trockenbau','gipskarton',null,'m2',0.72,'{"type":"standard","thickness_mm":12.5,"width_mm":600,"length_mm":1200,"area_m2":0.72,"required_terms":["gipskarton"],"excluded_terms":["feuchtraum","imprägniert","impragniert","gkbi","feuerschutz"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='gipskarton-standard-12-5-1200-600-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'rigips','rigips' from public.materials where slug='gipskarton-standard-12-5-1200-600-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'regips','regips' from public.materials where slug='gipskarton-standard-12-5-1200-600-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'rigipsplatte','rigipsplatte' from public.materials where slug='gipskarton-standard-12-5-1200-600-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'rigips platte','rigips platte' from public.materials where slug='gipskarton-standard-12-5-1200-600-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'gipsplatte','gipsplatte' from public.materials where slug='gipskarton-standard-12-5-1200-600-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'gipskarton','gipskarton' from public.materials where slug='gipskarton-standard-12-5-1200-600-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'gipskartonplatte','gipskartonplatte' from public.materials where slug='gipskarton-standard-12-5-1200-600-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'GK','gk' from public.materials where slug='gipskarton-standard-12-5-1200-600-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'GK Platte','gk platte' from public.materials where slug='gipskarton-standard-12-5-1200-600-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'trockenbauplatte','trockenbauplatte' from public.materials where slug='gipskarton-standard-12-5-1200-600-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:gipskarton-standard-12-5-2000-1250-v1'))::uuid,'gipskarton-standard-12-5-2000-1250-v1','Gipskartonplatte Standard 12,5 × 1250 × 2000 mm','Gipskartonplatte Standard 12,5 × 1250 × 2000 mm','Gipskartonplatte Standard 12,5 × 1250 × 2000 mm','Trockenbau','gipskarton',null,'m2',2.5,'{"type":"standard","thickness_mm":12.5,"width_mm":1250,"length_mm":2000,"area_m2":2.5,"required_terms":["gipskarton"],"excluded_terms":["feuchtraum","imprägniert","impragniert","gkbi","feuerschutz"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='gipskarton-standard-12-5-2000-1250-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'rigips','rigips' from public.materials where slug='gipskarton-standard-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'regips','regips' from public.materials where slug='gipskarton-standard-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'rigipsplatte','rigipsplatte' from public.materials where slug='gipskarton-standard-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'rigips platte','rigips platte' from public.materials where slug='gipskarton-standard-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'gipsplatte','gipsplatte' from public.materials where slug='gipskarton-standard-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'gipskarton','gipskarton' from public.materials where slug='gipskarton-standard-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'gipskartonplatte','gipskartonplatte' from public.materials where slug='gipskarton-standard-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'GK','gk' from public.materials where slug='gipskarton-standard-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'GK Platte','gk platte' from public.materials where slug='gipskarton-standard-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'trockenbauplatte','trockenbauplatte' from public.materials where slug='gipskarton-standard-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:gipskarton-feuchtraum-12-5-2000-1250-v1'))::uuid,'gipskarton-feuchtraum-12-5-2000-1250-v1','Feuchtraum-Gipskartonplatte 12,5 × 1250 × 2000 mm','Feuchtraum-Gipskartonplatte 12,5 × 1250 × 2000 mm','Feuchtraum-Gipskartonplatte 12,5 × 1250 × 2000 mm','Trockenbau','gipskarton',null,'m2',2.5,'{"type":"feuchtraum","thickness_mm":12.5,"width_mm":1250,"length_mm":2000,"area_m2":2.5,"required_terms":["feuchtraum"],"excluded_terms":["feuerschutz"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='gipskarton-feuchtraum-12-5-2000-1250-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'feuchtraumplatte','feuchtraumplatte' from public.materials where slug='gipskarton-feuchtraum-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'grüne rigips','gruene rigips' from public.materials where slug='gipskarton-feuchtraum-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'gkbi','gkbi' from public.materials where slug='gipskarton-feuchtraum-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'rigips feuchtraum','rigips feuchtraum' from public.materials where slug='gipskarton-feuchtraum-12-5-2000-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:osb3-18-2500-1250-v1'))::uuid,'osb3-18-2500-1250-v1','OSB/3 Verlegeplatte 18 × 1250 × 2500 mm, Nut und Feder','OSB/3 Verlegeplatte 18 × 1250 × 2500 mm, Nut und Feder','OSB/3 Verlegeplatte 18 × 1250 × 2500 mm, Nut und Feder','Holzbau','osb',null,'m2',3.125,'{"type":"osb3","thickness_mm":18,"width_mm":1250,"length_mm":2500,"area_m2":3.125,"required_terms":["osb","nut","feder"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='osb3-18-2500-1250-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'OSB','osb' from public.materials where slug='osb3-18-2500-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'osb platte','osb platte' from public.materials where slug='osb3-18-2500-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'grobspanplatte','grobspanplatte' from public.materials where slug='osb3-18-2500-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'verlegeplatte','verlegeplatte' from public.materials where slug='osb3-18-2500-1250-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:ud28-27-3000-v1'))::uuid,'ud28-27-3000-v1','UD-Wandprofil 28/27 × 3000 mm','UD-Wandprofil 28/27 × 3000 mm','UD-Wandprofil 28/27 × 3000 mm','Trockenbau','ud-profil',null,'m',3,'{"type":"ud","length_mm":3000,"width_mm":28,"height_mm":27,"required_terms":["ud"],"excluded_terms":["cd","cw","uw"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='ud28-27-3000-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'UD','ud' from public.materials where slug='ud28-27-3000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'UD 28','ud 28' from public.materials where slug='ud28-27-3000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'UD Profil','ud profil' from public.materials where slug='ud28-27-3000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'wandanschlussprofil','wandanschlussprofil' from public.materials where slug='ud28-27-3000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:cd60-27-3000-v1'))::uuid,'cd60-27-3000-v1','CD-Deckenprofil 60/27 × 3000 mm','CD-Deckenprofil 60/27 × 3000 mm','CD-Deckenprofil 60/27 × 3000 mm','Trockenbau','cd-profil',null,'m',3,'{"type":"cd","length_mm":3000,"width_mm":60,"height_mm":27,"required_terms":["cd"],"excluded_terms":["ud","cw","uw"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='cd60-27-3000-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'CD','cd' from public.materials where slug='cd60-27-3000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'CD Profil','cd profil' from public.materials where slug='cd60-27-3000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'CD 60/27','cd 60 27' from public.materials where slug='cd60-27-3000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'CD Profil 60/27','cd profil 60 27' from public.materials where slug='cd60-27-3000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'deckenprofil','deckenprofil' from public.materials where slug='cd60-27-3000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:trennwandband-30-3-30000-v1'))::uuid,'trennwandband-30-3-30000-v1','Trennwandband 30 mm × 3 mm × 30 m, selbstklebend','Trennwandband 30 mm × 3 mm × 30 m, selbstklebend','Trennwandband 30 mm × 3 mm × 30 m, selbstklebend','Trockenbau','trennwandband',null,'m',30,'{"type":"trennwandband","width_mm":30,"thickness_mm":3,"length_mm":30000,"required_terms":["trennwandband","selbstklebend"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='trennwandband-30-3-30000-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'trennwandband','trennwandband' from public.materials where slug='trennwandband-30-3-30000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'dichtungsband trockenbau','dichtungsband trockenbau' from public.materials where slug='trennwandband-30-3-30000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:dichtungsband-50-3-30000-v1'))::uuid,'dichtungsband-50-3-30000-v1','Dichtungsband 50 mm × 3 mm × 30 m, selbstklebend','Dichtungsband 50 mm × 3 mm × 30 m, selbstklebend','Dichtungsband 50 mm × 3 mm × 30 m, selbstklebend','Trockenbau','dichtungsband',null,'m',30,'{"type":"dichtungsband","width_mm":50,"thickness_mm":3,"length_mm":30000,"required_terms":["dichtungsband","selbstklebend"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='dichtungsband-50-3-30000-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'dichtungsband','dichtungsband' from public.materials where slug='dichtungsband-50-3-30000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'profilband','profilband' from public.materials where slug='dichtungsband-50-3-30000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:direktabhaenger-cd60-125-1-v1'))::uuid,'direktabhaenger-cd60-125-1-v1','Direktabhänger CD 60/27, 125 mm, 1 Stück','Direktabhänger CD 60/27, 125 mm, 1 Stück','Direktabhänger CD 60/27, 125 mm, 1 Stück','Trockenbau','direktabhaenger',null,'piece',1,'{"type":"direktabhaenger","length_mm":125,"pieces":1,"profile":"cd60/27","required_terms":["direktabhänger","60","27"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='direktabhaenger-cd60-125-1-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'direktabhänger','direktabhaenger' from public.materials where slug='direktabhaenger-cd60-125-1-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'direktabhaenger','direktabhaenger' from public.materials where slug='direktabhaenger-cd60-125-1-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'abhänger','abhaenger' from public.materials where slug='direktabhaenger-cd60-125-1-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:nonius-unterteil-cd60-130-1-v1'))::uuid,'nonius-unterteil-cd60-130-1-v1','Noniusabhänger Unterteil CD 60/27, 130 mm, 1 Stück','Noniusabhänger Unterteil CD 60/27, 130 mm, 1 Stück','Noniusabhänger Unterteil CD 60/27, 130 mm, 1 Stück','Trockenbau','noniusabhaenger',null,'piece',1,'{"type":"nonius-unterteil","length_mm":130,"pieces":1,"profile":"cd60/27","required_terms":["nonius","unterteil","60","27"],"excluded_terms":["oberteil"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='nonius-unterteil-cd60-130-1-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'noniusabhänger','noniusabhaenger' from public.materials where slug='nonius-unterteil-cd60-130-1-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'noniusabhaenger','noniusabhaenger' from public.materials where slug='nonius-unterteil-cd60-130-1-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'nonius unterteil','nonius unterteil' from public.materials where slug='nonius-unterteil-cd60-130-1-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:knauf-uniflott-5kg-v1'))::uuid,'knauf-uniflott-5kg-v1','Knauf Uniflott Fugenspachtel, 5 kg','Knauf Uniflott Fugenspachtel, 5 kg','Knauf Uniflott Fugenspachtel, 5 kg','Spachtelmassen','uniflott','Knauf','kg',5,'{"type":"fugenspachtel","weight_kg":5,"required_terms":["knauf","uniflott"],"excluded_terms":["finish","imprägniert","impragniert"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='knauf-uniflott-5kg-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'uniflott','uniflott' from public.materials where slug='knauf-uniflott-5kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'fugenspachtel','fugenspachtel' from public.materials where slug='knauf-uniflott-5kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'knauf spachtel','knauf spachtel' from public.materials where slug='knauf-uniflott-5kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:knauf-uniflott-25kg-v1'))::uuid,'knauf-uniflott-25kg-v1','Knauf Uniflott Fugenspachtel, 25 kg','Knauf Uniflott Fugenspachtel, 25 kg','Knauf Uniflott Fugenspachtel, 25 kg','Spachtelmassen','uniflott','Knauf','kg',25,'{"type":"fugenspachtel","weight_kg":25,"required_terms":["knauf","uniflott"],"excluded_terms":["finish","imprägniert","impragniert"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='knauf-uniflott-25kg-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'uniflott','uniflott' from public.materials where slug='knauf-uniflott-25kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'fugenspachtel','fugenspachtel' from public.materials where slug='knauf-uniflott-25kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:knauf-uniflott-finish-8kg-v1'))::uuid,'knauf-uniflott-finish-8kg-v1','Knauf Uniflott Finish Fertigspachtel, 8 kg','Knauf Uniflott Finish Fertigspachtel, 8 kg','Knauf Uniflott Finish Fertigspachtel, 8 kg','Spachtelmassen','uniflott-finish','Knauf','kg',8,'{"type":"fertigspachtel","weight_kg":8,"required_terms":["knauf","uniflott","finish"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='knauf-uniflott-finish-8kg-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'finish','finish' from public.materials where slug='knauf-uniflott-finish-8kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'uniflott finish','uniflott finish' from public.materials where slug='knauf-uniflott-finish-8kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'fertigspachtel','fertigspachtel' from public.materials where slug='knauf-uniflott-finish-8kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:rigips-vario-5kg-v1'))::uuid,'rigips-vario-5kg-v1','Rigips VARIO Fugenspachtel, 5 kg','Rigips VARIO Fugenspachtel, 5 kg','Rigips VARIO Fugenspachtel, 5 kg','Spachtelmassen','vario','Rigips','kg',5,'{"type":"fugenspachtel","weight_kg":5,"required_terms":["rigips","vario"],"excluded_terms":["hydro"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='rigips-vario-5kg-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'VARIO','vario' from public.materials where slug='rigips-vario-5kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'rigips vario','rigips vario' from public.materials where slug='rigips-vario-5kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'fugenspachtel','fugenspachtel' from public.materials where slug='rigips-vario-5kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:knauf-rotband-30kg-v1'))::uuid,'knauf-rotband-30kg-v1','Knauf Rotband Haftputzgips, 30 kg','Knauf Rotband Haftputzgips, 30 kg','Knauf Rotband Haftputzgips, 30 kg','Putze','rotband','Knauf','kg',30,'{"type":"haftputzgips","weight_kg":30,"required_terms":["knauf","rotband"],"excluded_terms":["pro","finish","flächen","flaechen","renovier"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='knauf-rotband-30kg-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'rotband','rotband' from public.materials where slug='knauf-rotband-30kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'haftputz','haftputz' from public.materials where slug='knauf-rotband-30kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'gipsputz','gipsputz' from public.materials where slug='knauf-rotband-30kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:knauf-rotband-25kg-v1'))::uuid,'knauf-rotband-25kg-v1','Knauf Rotband Haftputzgips, 25 kg','Knauf Rotband Haftputzgips, 25 kg','Knauf Rotband Haftputzgips, 25 kg','Putze','rotband','Knauf','kg',25,'{"type":"haftputzgips","weight_kg":25,"required_terms":["knauf","rotband"],"excluded_terms":["pro","finish","flächen","flaechen","renovier"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='knauf-rotband-25kg-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'rotband','rotband' from public.materials where slug='knauf-rotband-25kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'haftputz','haftputz' from public.materials where slug='knauf-rotband-25kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'gipsputz','gipsputz' from public.materials where slug='knauf-rotband-25kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:knauf-perlfix-30kg-v1'))::uuid,'knauf-perlfix-30kg-v1','Knauf Perlfix Ansetzgips, 30 kg','Knauf Perlfix Ansetzgips, 30 kg','Knauf Perlfix Ansetzgips, 30 kg','Putze','perlfix','Knauf','kg',30,'{"type":"ansetzgips","weight_kg":30,"required_terms":["knauf","perlfix"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='knauf-perlfix-30kg-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'perlfix','perlfix' from public.materials where slug='knauf-perlfix-30kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'ansetzgips','ansetzgips' from public.materials where slug='knauf-perlfix-30kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'gipskleber','gipskleber' from public.materials where slug='knauf-perlfix-30kg-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:knauf-tiefengrund-5l-v1'))::uuid,'knauf-tiefengrund-5l-v1','Knauf Tiefengrund, 5 l','Knauf Tiefengrund, 5 l','Knauf Tiefengrund, 5 l','Grundierungen','tiefengrund','Knauf','l',5,'{"type":"tiefengrund","volume_l":5,"required_terms":["knauf","tiefengrund"],"excluded_terms":["konzentrat"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='knauf-tiefengrund-5l-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'tiefengrund','tiefengrund' from public.materials where slug='knauf-tiefengrund-5l-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'grundierung','grundierung' from public.materials where slug='knauf-tiefengrund-5l-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'tiefgrund','tiefgrund' from public.materials where slug='knauf-tiefengrund-5l-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:haftgrund-quarzsand-5l-v1'))::uuid,'haftgrund-quarzsand-5l-v1','Haftgrund mit Quarzsand, gebrauchsfertig, 5 l','Haftgrund mit Quarzsand, gebrauchsfertig, 5 l','Haftgrund mit Quarzsand, gebrauchsfertig, 5 l','Grundierungen','haftgrund',null,'l',5,'{"type":"haftgrund-quarzsand","volume_l":5,"required_terms":["haftgrund","quarzsand"],"excluded_terms":["konzentrat"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='haftgrund-quarzsand-5l-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'haftgrund','haftgrund' from public.materials where slug='haftgrund-quarzsand-5l-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'haftbrücke','haftbruecke' from public.materials where slug='haftgrund-quarzsand-5l-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'haftbruecke','haftbruecke' from public.materials where slug='haftgrund-quarzsand-5l-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:acryl-weiss-310ml-v1'))::uuid,'acryl-weiss-310ml-v1','Acryl-Dichtstoff weiß, überstreichbar, 310 ml','Acryl-Dichtstoff weiß, überstreichbar, 310 ml','Acryl-Dichtstoff weiß, überstreichbar, 310 ml','Dichtstoffe','acryl',null,'l',0.31,'{"type":"acryl","volume_l":0.31,"color":"weiss","required_terms":["acryl","weiß","überstreichbar"],"excluded_terms":["silikon","parkett","transparent"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='acryl-weiss-310ml-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'acryl','acryl' from public.materials where slug='acryl-weiss-310ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'acryl 310','acryl 310' from public.materials where slug='acryl-weiss-310ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'acryl 310 ml','acryl 310 ml' from public.materials where slug='acryl-weiss-310ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'maleracryl','maleracryl' from public.materials where slug='acryl-weiss-310ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:tn-3-5-25-1000-v1'))::uuid,'tn-3-5-25-1000-v1','Schnellbauschrauben TN 3,5 × 25 mm, Feingewinde, 1000 Stück','Schnellbauschrauben TN 3,5 × 25 mm, Feingewinde, 1000 Stück','Schnellbauschrauben TN 3,5 × 25 mm, Feingewinde, 1000 Stück','Befestigung','tn-schrauben',null,'piece',1000,'{"type":"tn","diameter_mm":3.5,"length_mm":25,"pieces":1000,"required_terms":["tn","feingewinde"],"excluded_terms":["grobgewinde","tb"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='tn-3-5-25-1000-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'TN 25','tn 25' from public.materials where slug='tn-3-5-25-1000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'TN25','tn25' from public.materials where slug='tn-3-5-25-1000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'schnellbauschrauben','schnellbauschrauben' from public.materials where slug='tn-3-5-25-1000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'rigipsschrauben','rigipsschrauben' from public.materials where slug='tn-3-5-25-1000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:tn-3-5-35-1000-v1'))::uuid,'tn-3-5-35-1000-v1','Schnellbauschrauben TN 3,5 × 35 mm, Feingewinde, 1000 Stück','Schnellbauschrauben TN 3,5 × 35 mm, Feingewinde, 1000 Stück','Schnellbauschrauben TN 3,5 × 35 mm, Feingewinde, 1000 Stück','Befestigung','tn-schrauben',null,'piece',1000,'{"type":"tn","diameter_mm":3.5,"length_mm":35,"pieces":1000,"required_terms":["tn","feingewinde"],"excluded_terms":["grobgewinde","tb"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='tn-3-5-35-1000-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'TN 35','tn 35' from public.materials where slug='tn-3-5-35-1000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'TN35','tn35' from public.materials where slug='tn-3-5-35-1000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'schnellbauschrauben','schnellbauschrauben' from public.materials where slug='tn-3-5-35-1000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'rigipsschrauben','rigipsschrauben' from public.materials where slug='tn-3-5-35-1000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:glaswolle-035-120-6m2-v1'))::uuid,'glaswolle-035-120-6m2-v1','Glaswolle-Klemmfilz WLG 035, 120 × 1200 × 5000 mm, 6 m²/Rolle','Glaswolle-Klemmfilz WLG 035, 120 × 1200 × 5000 mm, 6 m²/Rolle','Glaswolle-Klemmfilz WLG 035, 120 × 1200 × 5000 mm, 6 m²/Rolle','Dämmung','mineralwolle',null,'m2',6,'{"type":"glaswolle-klemmfilz","thickness_mm":120,"width_mm":1200,"length_mm":5000,"pieces":1,"thermal_conductivity":0.035,"area_m2":6,"required_terms":["glaswolle","035"],"excluded_terms":["steinwolle"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='glaswolle-035-120-6m2-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'mineralwolle','mineralwolle' from public.materials where slug='glaswolle-035-120-6m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'dämmung','daemmung' from public.materials where slug='glaswolle-035-120-6m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'daemmung','daemmung' from public.materials where slug='glaswolle-035-120-6m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'klemmfilz','klemmfilz' from public.materials where slug='glaswolle-035-120-6m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'glaswolle','glaswolle' from public.materials where slug='glaswolle-035-120-6m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:dampfbremse-sd2-1500-50000-v1'))::uuid,'dampfbremse-sd2-1500-50000-v1','Dampfbremse sd 2 m, 1,5 × 50 m, 75 m²/Rolle','Dampfbremse sd 2 m, 1,5 × 50 m, 75 m²/Rolle','Dampfbremse sd 2 m, 1,5 × 50 m, 75 m²/Rolle','Dämmung','dampfbremse',null,'m2',75,'{"type":"dampfbremse","sd_m":2,"width_mm":1500,"length_mm":50000,"area_m2":75,"required_terms":["dampfbremse"],"excluded_terms":["variabel","klimamembran"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='dampfbremse-sd2-1500-50000-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'dampfbremse','dampfbremse' from public.materials where slug='dampfbremse-sd2-1500-50000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'dampfbremsfolie','dampfbremsfolie' from public.materials where slug='dampfbremse-sd2-1500-50000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:pe-folie-200-2000-50000-v1'))::uuid,'pe-folie-200-2000-50000-v1','PE-Baufolie 200 µm, 2 × 50 m, 100 m²/Rolle','PE-Baufolie 200 µm, 2 × 50 m, 100 m²/Rolle','PE-Baufolie 200 µm, 2 × 50 m, 100 m²/Rolle','Folien','pe-folie',null,'m2',100,'{"type":"pe-baufolie","thickness_mm":0.2,"width_mm":2000,"length_mm":50000,"area_m2":100,"required_terms":["pe","folie"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='pe-folie-200-2000-50000-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'PE Folie','pe folie' from public.materials where slug='pe-folie-200-2000-50000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'PE-Folie','pe folie' from public.materials where slug='pe-folie-200-2000-50000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'baufolie','baufolie' from public.materials where slug='pe-folie-200-2000-50000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'polyethylenfolie','polyethylenfolie' from public.materials where slug='pe-folie-200-2000-50000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:randdaemmstreifen-8-150-25000-v1'))::uuid,'randdaemmstreifen-8-150-25000-v1','Randdämmstreifen 8 × 150 mm × 25 m, mit Folienlasche','Randdämmstreifen 8 × 150 mm × 25 m, mit Folienlasche','Randdämmstreifen 8 × 150 mm × 25 m, mit Folienlasche','Estrich','randdaemmstreifen',null,'m',25,'{"type":"randdaemmstreifen","thickness_mm":8,"width_mm":150,"length_mm":25000,"required_terms":["randdämmstreifen","folienlasche"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='randdaemmstreifen-8-150-25000-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'randdämmstreifen','randdaemmstreifen' from public.materials where slug='randdaemmstreifen-8-150-25000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'randdaemmstreifen','randdaemmstreifen' from public.materials where slug='randdaemmstreifen-8-150-25000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'estrichrandstreifen','estrichrandstreifen' from public.materials where slug='randdaemmstreifen-8-150-25000-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:cd60-27-3100-v1'))::uuid,'cd60-27-3100-v1','CD-Deckenprofil 60/27 × 3100 mm','CD-Deckenprofil 60/27 × 3100 mm','CD-Deckenprofil 60/27 × 3100 mm','Trockenbau','cd-profil',null,'m',3.1,'{"type":"cd","length_mm":3100,"width_mm":60,"height_mm":27,"required_terms":["cd"],"excluded_terms":["ud","cw","uw"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='cd60-27-3100-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'CD','cd' from public.materials where slug='cd60-27-3100-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'CD Profil','cd profil' from public.materials where slug='cd60-27-3100-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'CD 60/27','cd 60 27' from public.materials where slug='cd60-27-3100-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'CD Profil 60/27','cd profil 60 27' from public.materials where slug='cd60-27-3100-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'deckenprofil','deckenprofil' from public.materials where slug='cd60-27-3100-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:glaswolle-035-120-5-28m2-v1'))::uuid,'glaswolle-035-120-5-28m2-v1','Glaswolle-Klemmfilz WLG 035, 120 × 1200 × 4400 mm, 5,28 m²/Rolle','Glaswolle-Klemmfilz WLG 035, 120 × 1200 × 4400 mm, 5,28 m²/Rolle','Glaswolle-Klemmfilz WLG 035, 120 × 1200 × 4400 mm, 5,28 m²/Rolle','Dämmung','mineralwolle',null,'m2',5.28,'{"type":"glaswolle-klemmfilz","thickness_mm":120,"width_mm":1200,"length_mm":4400,"pieces":1,"thermal_conductivity":0.035,"area_m2":5.28,"required_terms":["glaswolle","035"],"excluded_terms":["steinwolle"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='glaswolle-035-120-5-28m2-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'mineralwolle','mineralwolle' from public.materials where slug='glaswolle-035-120-5-28m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'dämmung','daemmung' from public.materials where slug='glaswolle-035-120-5-28m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'daemmung','daemmung' from public.materials where slug='glaswolle-035-120-5-28m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'klemmfilz','klemmfilz' from public.materials where slug='glaswolle-035-120-5-28m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'glaswolle','glaswolle' from public.materials where slug='glaswolle-035-120-5-28m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:sanitaer-silikon-acetat-weiss-310ml-v1'))::uuid,'sanitaer-silikon-acetat-weiss-310ml-v1','Sanitär-Silikon weiß, essigvernetzend, 310 ml','Sanitär-Silikon weiß, essigvernetzend, 310 ml','Sanitär Silikon weiß 310 ml essig','Dichtstoffe','sanitaer-silikon-acetat',null,'l',0.31,'{"type":"sanitaer-silikon-acetat","volume_l":0.31,"color":"weiss","required_terms":["silikon","sanitär","essig"],"excluded_terms":["neutral","acryl","entferner"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='sanitaer-silikon-acetat-weiss-310ml-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'silikon','silikon' from public.materials where slug='sanitaer-silikon-acetat-weiss-310ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'sanitärsilikon','sanitaersilikon' from public.materials where slug='sanitaer-silikon-acetat-weiss-310ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'sanitär silikon','sanitaer silikon' from public.materials where slug='sanitaer-silikon-acetat-weiss-310ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'silikon weiß 310 ml','silikon weiss 310 ml' from public.materials where slug='sanitaer-silikon-acetat-weiss-310ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'essigvernetzendes silikon','essigvernetzendes silikon' from public.materials where slug='sanitaer-silikon-acetat-weiss-310ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:glaswolle-035-120-5-76m2-v1'))::uuid,'glaswolle-035-120-5-76m2-v1','Glaswolle-Klemmfilz WLG 035, 120 × 1200 × 4800 mm, 5,76 m²/Rolle','Glaswolle-Klemmfilz WLG 035, 120 × 1200 × 4800 mm, 5,76 m²/Rolle','Glaswolle-Klemmfilz WLG 035, 120 × 1200 × 4800 mm, 5,76 m²/Rolle','Dämmung','mineralwolle',null,'m2',5.76,'{"type":"glaswolle-klemmfilz","thickness_mm":120,"width_mm":1200,"length_mm":4800,"pieces":1,"thermal_conductivity":0.035,"area_m2":5.76,"required_terms":["glaswolle","035"],"excluded_terms":["steinwolle"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='glaswolle-035-120-5-76m2-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'mineralwolle','mineralwolle' from public.materials where slug='glaswolle-035-120-5-76m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'dämmung','daemmung' from public.materials where slug='glaswolle-035-120-5-76m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'daemmung','daemmung' from public.materials where slug='glaswolle-035-120-5-76m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'klemmfilz','klemmfilz' from public.materials where slug='glaswolle-035-120-5-76m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'glaswolle','glaswolle' from public.materials where slug='glaswolle-035-120-5-76m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:pu-schaum-1k-b2-genius-750ml-v1'))::uuid,'pu-schaum-1k-b2-genius-750ml-v1','Soudal PU-Bauschaum 1K B2 Genius Gun beige, 750 ml','Soudal PU-Bauschaum 1K B2 Genius Gun beige, 750 ml','Soudal PU-Bauschaum 1K B2 Genius Gun beige, 750 ml','Bauschäume','pu-schaum','Soudal','l',0.75,'{"type":"1k-b2-genius","volume_l":0.75,"color":"beige","required_terms":["soudal","b2","genius","einkomponent"],"excluded_terms":["2k","reiniger"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='pu-schaum-1k-b2-genius-750ml-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'PU-Schaum','pu schaum' from public.materials where slug='pu-schaum-1k-b2-genius-750ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'Montageschaum','montageschaum' from public.materials where slug='pu-schaum-1k-b2-genius-750ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'Bauschaum','bauschaum' from public.materials where slug='pu-schaum-1k-b2-genius-750ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:acryl-weiss-300ml-v1'))::uuid,'acryl-weiss-300ml-v1','Acryl-Dichtstoff weiß, überstreichbar, 300 ml','Acryl-Dichtstoff weiß, überstreichbar, 300 ml','Acryl-Dichtstoff weiß, überstreichbar, 300 ml','Dichtstoffe','acryl',null,'l',0.3,'{"type":"acryl","volume_l":0.3,"color":"weiss","required_terms":["acryl","weiß","überstreichbar"],"excluded_terms":["silikon","parkett","transparent"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='acryl-weiss-300ml-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'Acryl 300','acryl 300' from public.materials where slug='acryl-weiss-300ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'Acryl 300 ml','acryl 300 ml' from public.materials where slug='acryl-weiss-300ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'Maleracryl 300 ml','maleracryl 300 ml' from public.materials where slug='acryl-weiss-300ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:acryl-weiss-280ml-v1'))::uuid,'acryl-weiss-280ml-v1','Acryl-Dichtstoff weiß, überstreichbar, 280 ml','Acryl-Dichtstoff weiß, überstreichbar, 280 ml','Acryl-Dichtstoff weiß, überstreichbar, 280 ml','Dichtstoffe','acryl',null,'l',0.28,'{"type":"acryl","volume_l":0.28,"color":"weiss","required_terms":["acryl","weiß","überstreichbar"],"excluded_terms":["silikon","parkett","transparent"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='acryl-weiss-280ml-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'Acryl 280','acryl 280' from public.materials where slug='acryl-weiss-280ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'Acryl 280 ml','acryl 280 ml' from public.materials where slug='acryl-weiss-280ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'Maleracryl 280 ml','maleracryl 280 ml' from public.materials where slug='acryl-weiss-280ml-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.materials(id,slug,name,suggestion_label,store_search_term,category,product_family,brand,base_unit,package_quantity,specs,canonical_version,active,exact_product,match_rules)
select (md5('baumarktfinder:steinwolle-sonorock-040-40-7-5m2-v1'))::uuid,'steinwolle-sonorock-040-40-7-5m2-v1','Rockwool Sonorock Steinwolle WLG 040, 40 × 625 × 1000 mm, 7,5 m²/Paket','Mineralwolle 40 mm – Rockwool Sonorock, 7,5 m²/Paket','Rockwool Sonorock Steinwolle 40 mm','Dämmung','mineralwolle','Rockwool','m2',7.5,'{"type":"steinwolle-trennwandplatte","thickness_mm":40,"width_mm":625,"length_mm":1000,"pieces":12,"area_m2":7.5,"thermal_conductivity":0.04,"required_terms":["steinwolle","sonorock"],"excluded_terms":["glaswolle"]}'::jsonb,1,true,true,'{}'::jsonb
where not exists(select 1 from public.materials where slug='steinwolle-sonorock-040-40-7-5m2-v1');
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'Mineralwolle 40 mm','mineralwolle 40 mm' from public.materials where slug='steinwolle-sonorock-040-40-7-5m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'Steinwolle 40mm','steinwolle 40mm' from public.materials where slug='steinwolle-sonorock-040-40-7-5m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'Sonorock 40','sonorock 40' from public.materials where slug='steinwolle-sonorock-040-40-7-5m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
insert into public.canonical_material_aliases(material_id,alias,normalized_alias) select id,'Trennwandplatte 40 mm','trennwandplatte 40 mm' from public.materials where slug='steinwolle-sonorock-040-40-7-5m2-v1' and canonical_version>=1 on conflict(material_id,normalized_alias) do nothing;
notify pgrst, 'reload schema';
commit;
